//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCRUDLib.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using SuperCRUDLib.Entities;
    using System.Collections.Generic;

    public partial class SuperRegistryEntities : DbContext
    {
        public SuperRegistryEntities()
            : base("name=SuperRegistryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ability> Abilities { get; set; }
        public virtual DbSet<Affinity> Affinities { get; set; }
        public virtual DbSet<Alias> Aliases { get; set; }
        public virtual DbSet<Background> Backgrounds { get; set; }
        public virtual DbSet<Origin> Origins { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Superhero> Superheroes { get; set; }
    
        public virtual ObjectResult<sp_SelectPageOfSuperheros_Result> sp_SelectPageOfSuperheros(Nullable<int> pageNo, Nullable<int> pageSize, string filter)
        {
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("pageNo", pageNo) :
                new ObjectParameter("pageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var filterParameter = filter != null ?
                new ObjectParameter("filter", filter) :
                new ObjectParameter("filter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SelectPageOfSuperheros_Result>("sp_SelectPageOfSuperheros", pageNoParameter, pageSizeParameter, filterParameter);
        }
    }
}
