//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCRUDLib.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Superhero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Superhero()
        {
            this.Backgrounds = new HashSet<Background>();
        }
    
        public int SuperheroID { get; set; }
        public Nullable<int> AffinityID { get; set; }
        public string Name { get; set; }
    
        public virtual Affinity Affinity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Background> Backgrounds { get; set; }
    }
}
