//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Super_CRUD_App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alias
    {
        public int AliasID { get; set; }
        public Nullable<int> BackgroundID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
    
        public virtual Background Background { get; set; }
    }
}
